// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using clinicProject;

#nullable disable

namespace clinicProject.data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241212112727_one-to-many")]
    partial class onetomany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassDoctorClassPatient", b =>
                {
                    b.Property<int>("doctorsid")
                        .HasColumnType("int");

                    b.Property<int>("patientsid")
                        .HasColumnType("int");

                    b.HasKey("doctorsid", "patientsid");

                    b.HasIndex("patientsid");

                    b.ToTable("ClassDoctorClassPatient");
                });

            modelBuilder.Entity("clinicProject.core.Entities.ClassDoctor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("businesshours")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("phone")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("doctors");
                });

            modelBuilder.Entity("clinicProject.core.Entities.ClassPatient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("phone")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("patients");
                });

            modelBuilder.Entity("clinicProject.core.Entities.ClassRoute", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("doctorid")
                        .HasColumnType("int");

                    b.Property<string>("endTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("patientid")
                        .HasColumnType("int");

                    b.Property<string>("startTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("doctorid");

                    b.HasIndex("patientid");

                    b.ToTable("routes");
                });

            modelBuilder.Entity("ClassDoctorClassPatient", b =>
                {
                    b.HasOne("clinicProject.core.Entities.ClassDoctor", null)
                        .WithMany()
                        .HasForeignKey("doctorsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("clinicProject.core.Entities.ClassPatient", null)
                        .WithMany()
                        .HasForeignKey("patientsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("clinicProject.core.Entities.ClassRoute", b =>
                {
                    b.HasOne("clinicProject.core.Entities.ClassDoctor", "doctor")
                        .WithMany("Routes")
                        .HasForeignKey("doctorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("clinicProject.core.Entities.ClassPatient", "patient")
                        .WithMany("Routes")
                        .HasForeignKey("patientid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("clinicProject.core.Entities.ClassDoctor", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("clinicProject.core.Entities.ClassPatient", b =>
                {
                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
